# Nome e porta do servidor
# Configuração do Eureka Server
spring.application.name=eureka-server
server.port=8761

# Configurações para definir que esta aplicação é o Servidor (e não um cliente)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.com.netflix.eureka=INFO