spring:
  application:
    name: config-server
  profiles:
    active: native        # Lê configurações de arquivos locais (classpath:/config)
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
