# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/smartpath
spring.datasource.username=smartpath
spring.datasource.password=smartpath123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - Cria e atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Configuração Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Configuração Client Eureka
spring.application.name=logic-controller
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuração do RabbitMQ (Nova Porta)
spring.rabbitmq.port=5673

# Porta do Servidor (Evitando conflito com a porta 8080)
server.port=8082